= Web Deploy 201 [Intermediate]
:description: Intermediate guide to deploying web apps
:no_header:
:version: 1.0.0
:author: Robert Bornschein
:autor:email: bornirobert@aol.de
:git-repo: https://my-git-repo 
:aprox-time-for-course: 60min
:notProjectName: how to get your simple static webpage hosted somewhere for free
:references:
https://gist.github.com/katendeglory/88b083c6edb37d0e2b1ac942e1f93ab6, 
:attribute-missing: drop

== Table of content

[upperroman]
. <<Quick Foreword, Quick Foreword>>
. <<Setup, Setup>>
  * <<Choosing a cloud hosting provider, cloud hosting provider>>
  * <<Choosing hardware, Choosing hardware>>
  * <<Logging onto your new server,Logging onto your new server>>
  * <<Creating a user, Creating a user>>
  * <<Updating the app store, Updating the app store>>
  * <<Installing dependencies, Installing dependencies>>
  * <<Starting Nginx, Starting Nginx>>
  * <<Setting up firewall, Setting up firewall>>
  * <<Adding increased security, Adding increased security>>
. <<Structure, Structure>>
  * <<Creating some directories, Creating some directories>>
  * <<Running a sample api - optional, optional>>
. <<Nginx Setup, Nginx>>
  * <<Reloading nginx, Reloading nginx>>
. <<Domain, Domain>>
. <<Certbot, Certbot>>
. <<Last words, Last words>>

= Quick Foreword

This is not a "_{notProjectName}_" quick guide. This guide will be teaching how to set up your own server, for ease of use and future deployments. If you are looking for that feel free to check out our https://google.com/[beginner course]. To follow along with this a remote server is strongly recommended, feel free to use a local server if you fancy. We will be teaching you how to set up a new remote server if you currently do not own one. For the sake of this course, we will be sticking to a standard Ubuntu 18.04 server. 
If you know other Linux-based distributions like Debian, Centos, arch, etc. feel free to use those.
This course will roughly take about {aprox-time-for-course}.

= Setup

[quote]
____
The way of the cloud.
____

== Choosing a cloud hosting provider
I prefer https://www.digitalocean.com/[digital ocean] as a cloud server hoster service, mainly due to the amount of free credit I was given thanks to the https://education.github.com/pack[github goodie bag] due to my college application. Other services would be https://www.linode.com/[linode] and https://aws.amazon.com/[AWS].

== Choosing hardware
Once you create an account over at one of those sites. You would have to create a _container_ of some sort.  
https://www.digitalocean.com/[Digital ocean] refers to this as a droplet, as will I from now.
A droplet is basically a server, when creating a droplet, choose to your liking. One option to look out for is where the server will be hosted. Close to you means lower ping. You can decide which os it will be on that droplet. For the remainder of this course, I will be demonstrating the workflow on Ubuntu 18.04. For this particular example, I chose a droplet in the 5$/month price range, which has a 1GB of memory, which is enough for a single web application and a hybrid of multiple web apps, be those static pages and or served web apps like a React.js application.

== Logging onto your new server
You now want to set it up. For that, we need a connection to the server first. On Mac OS and Linux, this is simply done via the command line. Regardless of how you set up the authentication, either via password or ssh-key - you do the following.

```bash
ssh root@yourIpAdressHere
```

For windows, this may result in having to use a third-party application like https://www.putty.org/[putty].

In case you are wondering why we use `root@` in front of the ip address, this simply specifies the username on that machine. You can think of a server like a normal desktop pc, without the desktop, without the monitor to it, you only have access to the console.

== Creating a user

We _add_ a user, give it sudo privileges by _adding Group_ sudo to the username, then _switch user_ to that newly created one.
```bash
adduser yourUsernameOfChoice
usermod -aG sudo yourUsernameOfChoice
su - yourUsernameOfChoice
```

== Updating the app store
```bash
sudo apt-get update
```

== Installing dependencies
```bash
sudo apt-get install git nginx ufw vim nano screen nodejs

sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install python-certbot-nginx
```

== Starting Nginx
```bash
sudo systemctl enable nginx # in case it's
sudo systemctl start nginx # not already running
```

== Setting up firewall

```bash
sudo ufw allow "Nginx HTTP"
sudo ufw allow "Nginx HTTPS"
sudo ufw allow "Nginx FULL"
sudo ufw allow OpenSSH
sudo ufw enable
```
At this point, you want to try reconnecting to your server via ssh-key or password.

== Adding increased security

You may use your text editor of choice, I choose vim.
You can also use nano. To do that simply replace `vi` with `nano`. +

```bash
sudo vi /etc/ssh/sshd_config
```
[quote]
____
Just in case https://itsfoss.com/how-to-exit-vim/[you get stuck in the vim editor].
____

In that file find the line that says
`PermitRootLogin yes` and change that to `PermitRootLogin no`.
This will remove the ability to login as root@your_ip_adress, which is what we want. Since you have to specify a username, it disallows brute-force attacks to root@your_ip_adress.

*ONLY DO THE FOLLOWING IF YOU HAVE PREVIOUSLY CONNECTED VIA SSH-KEY AND YOU KNOW WHAT YOU'RE DOING*. +
I would recommend also changing `PasswordAuthentication yes` to a `no`. +
If you plan on doing this, be sure to also copy your previous ssh-key from root to your user profile. +
Your local ssh-key would need to be located under `/home/<yourUserName>/.ssh/id_rsa.pub`. +
Most times, you do not have a local .ssh folder in your home directory. 
Be sure to create that via `mkdir /home/<yourUserName>/.ssh`. +
This would disallow brute-force attacks to yourusername@your_ip_adress too since it only accepts ssh-keys.

After saving the file, be sure to restart the sshd service via
```bash
sudo systemctl restart sshd
```
and try reconnecting afterward, to be safe.
If you cannot connect be sure to specify the username you wish to connect to beforehand, like so +
`ssh yourUserName@your_ip_adress:22`. The port is not necessary to be added via cli, as that is the default port for ssh connections. When using third-party applications such as `putty` for windows to connect to the remote server, it requires a port, which is 22 by default too.

By now, you should have a secure server setup.


= Structure

== Creating some directories
```bash
cd
mkdir -p dev/sample
mkdir prod
```

== Running a sample API - optional 
Feel free to skip to the <<nginx-setup, nginx setup>>, as this step is *purely educational* and may help in understanding the following nginx setup. +
Now go into the newly create sample directory and install express.js and open up a new index.js file. +

```bash
cd dev/sample
npm init -y
npm I express --save;
vi index.js
```

== index.js 
Be sure to write this to the file and save.
```js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

This will run the file you just saved (_index.js_) on a new https://linuxize.com/post/how-to-use-linux-screen/[screen]. 
```bash
screen -d -m node .
```
If you want to know how to close that screen be sure to look at https://linuxize.com/post/how-to-use-linux-screen/[this reference.]

= Nginx Setup
[quote]
____
Setting up your server as a reverse proxy 
____



You may be wondering what exactly is a https://www.nginx.com/resources/glossary/reverse-proxy-server/[reverse proxy]. To put it simply, it's redirects traffic to where you want it to go. This way you can handle a lot of different applications on just one server - fairly easy too.
`
```bash
cd /etc/nginx/sites-available
ls # you should see at least one file called default
# if you see a <yourIpAdress>.conf use that one in this example
```
You usually want to copy the default file to a new file of this namingScheme: `<yourDomain>.conf`. So if you already have a domain, be sure to do the following:

```
sudo cp -a defualt <yourDomainName>.conf
cd ../sites-enabled
sudo ln -s ../sites-available/<yourDomainName>.conf ./<yourDomainName>.conf
```
You have just created a sim-link from the *sites-available* to the *sites-enabled* directory. The sites-enabled directory is where nginx is looking for your config files. It's the convention to use it like this.

Say we want to have a web app, that built with any front-end framework (say react.js for example) which we want running on "/", we have a wiki which we will have at "/wiki" and an api at "/api".

`sudo vi default`
[pass]
<iframe
  src="https://carbon.now.sh/embed?bg=rgba%2851%2C155%2C216%2C1%29&t=panda-syntax&wt=none&l=nginx&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=server%2520%257B%250A%2520%2520%2520%2520...%2520content%250A%2520%2520%2520%2520%2523%2520Frontend%2520Application%2520With%2520react.js%250A%2520%2520%2520%2520location%2520%252F%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2523%2520since%2520this%2520is%2520a%2520react.js%2520application%2520we%2520need%2520to%2520serve%2520the%2520build%2520files%2520as%2520a%2520server%250A%2520%2520%2520%2520%2520%2520%2520%2520%2523%252C%2520so%2520we%2520need%2520to%2520listen%2520to%2520a%2520specific%2520port%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_set_header%2520X-Forwarded-For%2520%2524proxy_add_x_forwarded_for%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_set_header%2520X-Forwarded-Proto%2520%2524scheme%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_set_header%2520X-Real-IP%2520%2524remote_addr%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_set_header%2520Host%2520%2524http_host%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_pass%2520http%253A%252F%252F127.0.0.1%253A8080%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%250A%2520%2520%2520%2520%2523%2520Documentation%2520-%2520Wiki%250A%2520%2520%2520%2520location%2520%252Fwiki%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2523%2520since%2520you%2520usually%2520build%2520a%2520wiki%252C%2520this%2520will%2520be%2520most%2520likely%2520static%2520content.%250A%2520%2520%2520%2520%2520%2520%2520%2520%2523%2520that%27s%2520why%2520we%2520alias%2520the%2520root%2520to%2520the%2520given%2520directory.%250A%2520%2520%2520%2520%2520%2520%2520%2520alias%2520%252Fvar%252Fwww%252FreactApp%252Fwiki%253B%2520%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%250A%2520%2520%2520%2520%2523%2520Backend%2520Api%250A%2520%2520%2520%2520location%2520%252Fapi%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2523%2520this%2520will%2520also%2520be%2520a%2520server%250A%2520%2520%2520%2520%2520%2520%2520%2520%2523%2520this%2520one%2520will%2520be%2520listening%2520to%2520port%25203000%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_set_header%2520X-Forwarded-For%2520%2524proxy_add_x_forwarded_for%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_set_header%2520X-Forwarded-Proto%2520%2524scheme%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_set_header%2520X-Real-IP%2520%2524remote_addr%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_set_header%2520Host%2520%2524http_host%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520proxy_pass%2520http%253A%252F%252F127.0.0.1%253A3000%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520...%2520content%250A%257D"
  style="width: 1024px; height: 900px; border:0; transform: scale(1); overflow:hidden;"
  sandbox="allow-scripts allow-same-origin">
</iframe>

There will be other content in the file, which I tried to portray with the `...content` syntax.


== Reloading nginx
First, we test if there are any syntax issues. +
For that, we do `sudo nginx -t` and if there are no errors, feel free to proceed with `sudo systemctl restart nginx`.

= Domain

First, you need a custom domain. You can get some great deals on https://namecheap.com[namecheap.com] and https://name.com[name.com]. +
If you qualify for the https://education.github.com/pack[github goodie bag], feel free to check out their options. To my recollection, you can get a free .me domain for a year! That's a damn good deal. If not most domains cost roughly 5-8$ with the usual exceptions ranging from 0.23$ to 2000$ for popular choices.

After you get it, you would also need to add it to your server. In Digitalocean, this is fairly simple. In the project overview, you are greeted with an *add domain* button of sorts. There you would have to add a https://support.dnsimple.com/articles/a-record/[A-Record] with the domain pointing to the server's ip.

== Name servers

Once that is acquired, you need to point your domain's DNS to your providers' nameservers. Every cloud hosting provider always has a couple of nameservers associated with it. For digital ocean, for example, they are:

```
ns1.digitalocean.com
ns2.digitalocean.com
ns3.digitalocean.com
```

In this case, we would need to go to the place, where we'd gotten our domain from (say namecheap.com) and go to our domain admin panel. By default, the domain will point to the name servers associated with the domain provider (Namecheap in this example). You simply need to change those to those of your cloud hosting provider of choice. This will take some time to fully propagate. To see if this is done you'd need to use the ping command like so.

```
ping yourDomain
```

this is how a good response looks:
```
# for google for example
PING google.com (142.250.185.142) 56(84) bytes of data.
64 bytes from fra16s50-in-f14.1e100.net (142.250.185.142): icmp_seq=1 ttl=119 time=16.3 ms
```

If it finds your ip associated with the domain you can continue to the next step.


== Certbot
Certbot will add certificates to your domain. All you need to know for now is, those are necessary for a secure https connection. To do so, you must have done the following:

[lowerroman]
. added your yourDomain.conf files to `/etc/nginx/sites-enabled` via sim-link or regular file
. tested the syntax of your config file with `sudo nginx -t`
. waited for the nameservers to be fully propagated (usually takes up to a day)

If so, let's move on.

```bash
sudo certbot --nginx -d yourDomainHere -d yourOtherDomainHereIfYourHaveAddedMore -d evenSubDomainsGoGere -d theDStandsForDomain
```

Once that is done, it will tell you if there are any errors regarding the propagation of the nameservers or the syntax of the .conf files.

After this, you are prompted with a question, that has something to do with https support. Read the question, I suggest you always answer with `2`, for reasons I can't explain nor understand, yet it's what I do, and I've been told it's fairly important.

== Last words 
In case of confusion or errors, feel free to contact me on the https://discord.gg/SSRH28QxBT[discord] @rbrtbrnschn.
Hope you get it going. After that, it's a real breeze to set up anything new on a new subdomain. 

[quote]
____
Have a great day, you person on the internet.
_____