= README.adoc
:description: Intermediate guide to deploying web apps
:no_header:
:version: 1.0.0
:author: Robert Bornschein
:autor:email: bornirobert@aol.de
:git-repo: https://my-git-repo 
:aprox-time-for-course: 60min
:notProjectName: how to get your simple static webpage hosted somewhere for free


### Deploy for the web [intermediate]

=== Table of content
- <<foreword, foreword>>
- <<setup, setup>>
- <<structure, structure>>
- tips and tricks
- last words

=== SubModules

- ubuntu/unix 101
- nginx 101
- vim 101

[#foreword]
=== Quick Foreword

This is not a "_{notProjectName}_" quick guide. This guide will be teaching how to setup your own server, for ease of use and future deployments. If you are looking for that feel free to checkout our https://google.com/[beginner course]. To follow along with this a remote server is strongly recommended, feel free to use a local server if you fancy. We will be teaching you how to setup a new remote server, if you currently do not own one. For the sake of this course, we will be sticking to a standard Ubuntu 18.04 server. 
If you have knowledge of other linux based distrobutions like debian, centOs, arch, etc. feel free to use those.
This course will roughly take about {aprox-time-for-course}.

[#setup]
=== Setup
> The way of the cloud. 

==== Choosing a cloud hosting provider
I prefer https://www.digitalocean.com/[digital ocean] as a cloud server hoster service, mainly due to the amount of free credit I was given thanks to the https://education.github.com/pack[github goodie bag] due to my college application. Other services would be https://www.linode.com/[linode] and https://aws.amazon.com/[AWS].

==== Choosing hardware
Once you create an account over at one of those sites. You would have to create a _container_ of some sort.  
https://www.digitalocean.com/[Digital ocean] refers to this a droplet, as will I from now.
A droplet is basically a server, when creating a droplet, choose to your liking. Some options to look out for is where the server will be hosted. Close to you means lower ping. You can decide which os it will be on that droplet. For the remainder of this course I will be demonstrating the workflow on Ubuntu 18.04. For this particular example I chose a droplet in the 5$/month price range, which has a 1gb of memory, which is enough for a single web application and a hybrid of multiple web apps, be those static pages and or served web apps like a React.js application.

==== Logging onto your new server
You now want to set it up. For that we need a connection to the server first. On Mac OS and Linux, this is simply done via the command line. Regardless of how you setup the authentication, either via password or ssh-key - you do the following.

```bash
ssh root@yourIpAdressHere
```

For windows, this may result in having to use a thirdparty application like https://www.putty.org/[putty].

In case you are wondering why we use `root@` infront of the ip adress, this simply specifies the username on that machine. You can think of a server like a normal desktop pc, without the desktop, without the monitor to it, you only have access to the console.

==== Creating a user
> First things first

We _add_ a user, give it sudo priveleges by _adding Group_ sudo to the username, then _switch user_ to that newly created one.
```bash
adduser yourUsernameOfChoice
usermod -aG sudo yourUsernameOfChoice
su - yourUsernameOfChoice
```

==== Updating the app store
```bash
sudo apt-get update
```


[#structure]
=== Structure
